config/routes.rb
Rails.application.routes.draw do
  resources :mappings

  resources :keywords

  get '/search' => 'memes#search'
  get '/searchresults' => 'memes#searchresults'

  post '/donewsearch' => 'memes#performsearch'
  post '/delete_keyword/:id' => 'keywords#destroy'
  post '/delete_meme/:id' => 'memes#destroy'
  post '/delete_mapping/:id' => 'mappings#destroy'

  resources :memes

end

app/models/keyword.rb
class Keyword < ActiveRecord::Base
	has_many :mappings
	has_many :memes, :through => :mappings
end

app/models/mapping.rb
class Mapping < ActiveRecord::Base
	belongs_to :meme
	belongs_to :keyword
end

app/models/meme.rb
class Meme < ActiveRecord::Base
	has_many :mappings
	has_many :keywords, :through => :mappings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/keywords_controller.rb
class KeywordsController < ActionController::Base
  before_action :set_keyword, only: [:show, :edit, :update, :destroy]

  # GET /keywords
  # GET /keywords.json
  def index
    @keywords = Keyword.all
  end

  # GET /keywords/1
  # GET /keywords/1.json
  def show
  end

  # GET /keywords/new
  def new
    @keyword = Keyword.new
  end

  # GET /keywords/1/edit
  def edit
  end

  # POST /keywords
  # POST /keywords.json
  def create
    @keyword = Keyword.new(keyword_params)

    respond_to do |format|
      if @keyword.save
        format.html { redirect_to @keyword, notice: 'Keyword was successfully created.' }
        format.json { render :show, status: :created, location: @keyword }
      else
        format.html { render :new }
        format.json { render json: @keyword.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /keywords/1
  # PATCH/PUT /keywords/1.json
  def update
    respond_to do |format|
      if @keyword.update(keyword_params)
        format.html { redirect_to @keyword, notice: 'Keyword was successfully updated.' }
        format.json { render :show, status: :ok, location: @keyword }
      else
        format.html { render :edit }
        format.json { render json: @keyword.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /keywords/1
  # DELETE /keywords/1.json
  def destroy
    @keyword.destroy
    respond_to do |format|
      format.html { redirect_to keywords_url, notice: 'Keyword was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_keyword
      @keyword = Keyword.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def keyword_params
      params.require(:keyword).permit(:key)
    end
end

app/controllers/mappings_controller.rb
class MappingsController < ActionController::Base
  before_action :set_mapping, only: [:show, :edit, :update, :destroy]

  # GET /mappings
  # GET /mappings.json
  def index
    @mappings = Mapping.all
  end

  # GET /mappings/1
  # GET /mappings/1.json
  def show
  end

  # GET /mappings/new
  def new
    @mapping = Mapping.new
  end

  # GET /mappings/1/edit
  def edit
  end

  # POST /mappings
  # POST /mappings.json
  def create
    @mapping = Mapping.new(mapping_params)

    respond_to do |format|
      if @mapping.save
        format.html { redirect_to @mapping, notice: 'Mapping was successfully created.' }
        format.json { render :show, status: :created, location: @mapping }
      else
        format.html { render :new }
        format.json { render json: @mapping.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mappings/1
  # PATCH/PUT /mappings/1.json
  def update
    respond_to do |format|
      if @mapping.update(mapping_params)
        format.html { redirect_to @mapping, notice: 'Mapping was successfully updated.' }
        format.json { render :show, status: :ok, location: @mapping }
      else
        format.html { render :edit }
        format.json { render json: @mapping.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mappings/1
  # DELETE /mappings/1.json
  def destroy
    @mapping.destroy
    respond_to do |format|
      format.html { redirect_to mappings_url, notice: 'Mapping was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mapping
      @mapping = Mapping.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mapping_params
      params.require(:mapping).permit(:meme_id, :keyword_id)
    end
end

app/controllers/memes_controller.rb
 class MemesController < ActionController::Base
  before_action :set_meme, only: [:show, :edit, :update, :destroy]
    
  def search
    #DO NOTHING
    @color = ["blue", "red", "orange","green", "red" ,"gray", "blue"]
  end

  def performsearch
    #DO NOTHING
    session[:itemtosearch] = params[:itemtosearch]
    redirect_to '/searchresults'
  end

  def searchresults

    @raw_input = session[:itemtosearch].downcase

    @sanitized_input = @raw_input.gsub(/[^a-zA-Z0-9 ]/, "")
    @result = @sanitized_input.split(" ")
    @VObj = []
    @result.each do |item|
      @tmp = Keyword.where(:key => item).map(&:memes).flat_map {|i| i }
      @tmp.each do |el|
        @VObj << el.id
      end
    end
    h = Hash.new
    @VObj.each do |entry|
      h[entry] = h[entry].to_i + 1;
    end  

    @vector_to_sort = h.to_a
    @vector_to_sort.sort! { |a, b|  b[1] <=> a[1] }

    
    @results = Meme.find(@vector_to_sort.map { |innervector| innervector[0]}).reverse
    render 'searchresults'
  end
 
  # GET /memes
  # GET /memes.json
  def index
    @memes = Meme.all
  end

  # GET /memes/1
  # GET /memes/1.json
  def show
  end

  # GET /memes/new
  def new
    @meme = Meme.new

  end

  # GET /memes/1/edit
  def edit
  end

  # POST /memes
  # POST /memes.json
  def create
    @meme = Meme.new(meme_params)
    respond_to do |format|
      if @meme.save
        items = @meme.keywords_string.split(" ")
        items.each do |item| 
          attrs = { :key => item }
          @keyword = Keyword.new(attrs)
          if @keyword.save
            Mapping.create(:meme_id => @meme.id, :keyword_id => @keyword.id)
          end
        end
        format.html { redirect_to @meme, notice: 'Meme was successfully created. Keywords were successfully added' }
        format.json { render :show, status: :created, location: @meme }
      else
        format.html { render :new }
        format.json { render json: @meme.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /memes/1
  # PATCH/PUT /memes/1.json
  def update
    respond_to do |format|
      if @meme.update(meme_params)
        items = @meme.keywords_string.split(" ")
        items.each do |item| 
          attrs = { :key => item}
          @keyword = Keyword.new(attrs)
          if @keyword.save
            Mapping.create(:meme_id => @meme.id, :keyword_id => @keyword.id)
          end
        end
        format.html { redirect_to @meme, notice: 'Meme was successfully updated.' }
        format.json { render :show, status: :ok, location: @meme }
      else
        format.html { render :edit }
        format.json { render json: @meme.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /memes/1
  # DELETE /memes/1.json
  def destroy
    @meme.destroy
    respond_to do |format|
      format.html { redirect_to memes_url, notice: 'Meme was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meme
      @meme = Meme.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meme_params
      params.require(:meme).permit(:title, :keywords_string, :url, :rating)
    end

end

# Meme.last.keywords.map(&:key).join(' ')

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/keywords_helper.rb
module KeywordsHelper
end

app/helpers/mappings_helper.rb
module MappingsHelper
end

app/helpers/memes_helper.rb
module MemesHelper
end

app/views/keywords/_form.html.erb
<%= form_for(@keyword) do |f| %>
  <% if @keyword.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@keyword.errors.count, "error") %> prohibited this keyword from being saved:</h2>

      <ul>
      <% @keyword.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :key=string %><br>
    <%= f.text_field :key=string %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/keywords/edit.html.erb
<h1>Editing keyword</h1>

<%= render 'form' %>

<%= link_to 'Show', @keyword %> |
<%= link_to 'Back', keywords_path %>

app/views/keywords/index.html.erb
<h1>Listing keywords</h1>

<table>
  <thead>
    <tr>
      <th>Key=string</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @keywords.each do |keyword| %>
      <tr>
        <td><%= keyword.key %></td>
        <td><%= link_to 'Show', keyword %></td>
        <td><%= link_to 'Edit', edit_keyword_path(keyword) %></td>
        <td><form action="/delete_keyword/<%= keyword.id%>" method="post"><button>Delete</button></form></td
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Keyword', new_keyword_path %>

app/views/keywords/new.html.erb
<h1>New keyword</h1>

<%= render 'form' %>

<%= link_to 'Back', keywords_path %>

app/views/keywords/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Key=string:</strong>
  <%= @keyword.key=string %>
</p>

<%= link_to 'Edit', edit_keyword_path(@keyword) %> |
<%= link_to 'Back', keywords_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MemeSearchApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/mappings/_form.html.erb
<%= form_for(@mapping) do |f| %>
  <% if @mapping.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mapping.errors.count, "error") %> prohibited this mapping from being saved:</h2>

      <ul>
      <% @mapping.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :meme_id %><br>
    <%= f.number_field :meme_id %>
  </div>
  <div class="field">
    <%= f.label :keyword_id %><br>
    <%= f.number_field :keyword_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mappings/edit.html.erb
<h1>Editing mapping</h1>

<%= render 'form' %>

<%= link_to 'Show', @mapping %> |
<%= link_to 'Back', mappings_path %>

app/views/mappings/index.html.erb
<h1>Listing mappings</h1>

<table>
  <thead>
    <tr>
      <th>Meme</th>
      <th>Keyword</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mappings.each do |mapping| %>
      <tr>
        <td><%= mapping.meme_id %></td>
        <td><%= mapping.keyword_id %></td>
        <td><%= link_to 'Show', mapping %></td>
        <td><%= link_to 'Edit', edit_mapping_path(mapping) %></td>
        <td><form action="/delete_mapping/<%= mapping.id%>" method="post"><button>Delete</button></form></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mapping', new_mapping_path %>

app/views/mappings/new.html.erb
<h1>New mapping</h1>

<%= render 'form' %>

<%= link_to 'Back', mappings_path %>

app/views/mappings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Meme:</strong>
  <%= @mapping.meme_id %>
</p>

<p>
  <strong>Keyword:</strong>
  <%= @mapping.keyword_id %>
</p>

<%= link_to 'Edit', edit_mapping_path(@mapping) %> |
<%= link_to 'Back', mappings_path %>

app/views/memes/_form.html.erb
<%= form_for(@meme) do |f| %>
  <% if @meme.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@meme.errors.count, "error") %> prohibited this meme from being saved:</h2>

      <ul>
      <% @meme.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :keywords_string %><br>
    <%= f.text_area :keywords_string %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :rating %><br>
    <%= f.text_field :rating %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/memes/edit.html.erb
 <h1>Editing meme</h1>

<%= render 'form' %>

<%= link_to 'Show', @meme %> |
<%= link_to 'Back', memes_path %>

app/views/memes/index.html.erb
 <h1>Listing memes</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Keywords</th>
      <th>Url</th>
      <th>Rating</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @memes.each do |meme| %>
      <tr>
        <td><%= meme.title %></td>
        <td><%= meme.keywords_string %></td>
        <td><%= meme.url %></td>
        <td><%= meme.rating %></td>
        <td><%= link_to 'Show', meme %></td>
        <td><%= link_to 'Edit', edit_meme_path(meme) %></td>
        <td><form action="/delete_meme/<%= meme.id%>" method="post"><button>Delete</button></form></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Meme', new_meme_path %>

app/views/memes/new.html.erb
 <h1>New meme</h1>

<%= render 'form' %>

<%= link_to 'Back', memes_path %>

app/views/memes/performsearch.html.erb
<%= @text %>

app/views/memes/search.html.erb
<!DOCTYPE HTML>
<html lang="en">
  <head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap-theme.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Meme Law</title>
    <style>
      .padded {
          padding: 10px;
      }
      html, body{height:100%; margin:0;padding:0}
      .container-fluid{
        height:80%;
        display:table;
        width: 100%;
        padding: 0;
      }
      .row-fluid {height: 100%; display:table-cell; vertical-align: middle;}
      .centering {
        float:none;
        margin:0 auto;
      }
      @media (max-width: 768px) {
        .vertical-center:before {
          height: auto;
          /*/* Or */
          /*display: none;*/
        }
      }
    </style>
  </head>
  <body>
    <div class="container-fluid">
      <div class="row-fluid">
        <div class="centering text-center">
          <div class="container">
            <div class="SiteNameArea">
              <h1 style="font-family:Catull; font-size:90px;">
              <font color="<%=@color[0]%>">M</font><font color="<%=@color[1]%>">e</font><font color="<%=@color[2]%>">m</font><font color="<%=@color[3]%>">e</font><font color="<%=@color[4]%>">L</font><font color="<%=@color[5]%>">a</font><font color="<%=@color[6]%>">w</font>
              </h1>
              <div class="Quotes text-centered">
                <h3 style="font-family=Catull; font-size:17px;">
                  <font color="gray">
                    <i>The Google for memes :)</i>
                  </font>
                </h3>
              </div>
              <form action="/donewsearch" method="post">
                <input class="form-control input-sm" id="inputsm" type="text" name="itemtosearch" placeholder="Ce fel de meme-uri doriți să căutați ?">
                <br>
                <p>
                  <button type="submit" class="btn btn-default btn-sm"><b>Căutare meme<b></button>
                </p>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/memes/searchresults.html.erb
<!DOCTYPE HTML>
<html lang="en">

<head>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap-theme.min.css">
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>
    	Results of the search
    </title>
</head>
 <body>
 	<div class="container">
 		<div class="header" style="height:50px;">
			<div class="text-center" style="position:relative; top:10px">
				<p>The results of the search after: <%@result.each do |res|%> "<%=res.to_s%>" <%end%></p>
			</div>		
		</div>
		
		

		<%@results.each do |meme|%>
			<div class="panel panel-primary">
				<div class="panel-heading">
					<%=meme.title%>
				</div>
				<div class="panel-body">
					<img src="<%=meme.url%>" width="1105" height="800" align="center" >
				</div>
				<div class="panel-footer" style="height:50px">
					Rating: <%=meme.rating%>	
				</div>
			</div>
		<%end%>
	</div>
</html>

app/views/memes/show.html.erb
 <p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @meme.title %>
</p>

<p>
  <strong>Keywords:</strong>
  <%= @meme.keywords_string %>
</p>

<p>
  <strong>Url:</strong>
  <%= @meme.url %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @meme.rating %>
</p>

<%= link_to 'Edit', edit_meme_path(@meme) %> |
<%= link_to 'Back', memes_path %>